// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjggyeicijptwfxpydkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqZ2d5ZWljaWpwdHdmeHB5ZGt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDA4MDgsImV4cCI6MjA2NDM3NjgwOH0.EwPZcsmCVPCBwHh83SB2T5g3A_KUjfwVRRp_o3y6LbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);